version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/bonvih/website
hooks:
  ApplicationStop:
    - location: Scripts/application-stop.sh
      runas: root
  BeforeInstall:
    - location: Scripts/before-install.sh
      runas: root
  AfterInstall:
    - location: Scripts/after-install.sh
      runas: root
  ApplicationStart:
    - location: Scripts/application-start.sh
      runas: root
      timeout: 3600
