version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/bonvih/website
hooks:
  BeforeInstall:
    - location: Scripts/before-install.sh
  AfterInstall:
    - location: Scripts/after-install.sh
      timeout: 180
  ApplicationStart:
    - location: Scripts/service-start.sh
      timeout: 3600
